export function getLanguageFromLanguageId(languageId: string): string {
  if (!languageId) {
    return 'unknown';
  }

  const languageIdMap: { [key: string]: string } = {
    javascript: 'JavaScript',
    javascriptreact: 'JavaScript',
    typescript: 'TypeScript',
    typescriptreact: 'TypeScript',
    python: 'Python',
    java: 'Java',
    kotlin: 'Kotlin',
    scala: 'Scala',
    c: 'C',
    cpp: 'C++',
    csharp: 'C#',
    html: 'HTML',
    css: 'CSS',
    scss: 'SCSS',
    sass: 'Sass',
    less: 'Less',
    vue: 'Vue',
    svelte: 'Svelte',
    php: 'PHP',
    ruby: 'Ruby',
    go: 'Go',
    rust: 'Rust',
    swift: 'Swift',
    dart: 'Dart',
    shellscript: 'Shell',
    powershell: 'PowerShell',
    sql: 'SQL',
    r: 'R',
    matlab: 'MATLAB',
    lua: 'Lua',
    perl: 'Perl',
    haskell: 'Haskell',
    elixir: 'Elixir',
    fsharp: 'F#',
    clojure: 'Clojure',
    json: 'JSON',
    jsonc: 'JSON',
    xml: 'XML',
    yaml: 'YAML',
    toml: 'TOML',
    ini: 'INI',
    markdown: 'Markdown',
    latex: 'LaTeX',
    dockerfile: 'Dockerfile',
    makefile: 'Makefile',
    cmake: 'CMake',
    gradle: 'Gradle',
    properties: 'Properties',
    plaintext: 'Text',
    text: 'Text',
  };

  return languageIdMap[languageId.toLowerCase()] || 'Other';
}
